from collections.abc import Mapping

import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Connection

from dashboard.database import get_engine


TABELA_SERVICOS_MANUTENCAO_FILIAL = "servicos_executados_manutencao_filial"
TABELA_LEGADA_MANUTENCAO_FILIAL = "base_historica_manutencao_filial_teste"
PREFIXO_NUMERO_OS = "MF-"
LARGURA_NUMERO_OS = 8

CRIAR_TABELA_SQL = f"""
CREATE TABLE IF NOT EXISTS public.{TABELA_SERVICOS_MANUTENCAO_FILIAL} (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_ref date NOT NULL,
    data_competencia date NOT NULL,
    id_contrato varchar(50),
    contrato varchar(150) NOT NULL,
    id_operadora varchar(50),
    operadora varchar(150) NOT NULL,
    id_equipamento varchar(50),
    equipamento text NOT NULL,
    numero_serie text,
    id_servico_executado varchar(50),
    servico_executado text NOT NULL,
    qtd_servico integer NOT NULL DEFAULT 1 CHECK (qtd_servico > 0),
    defeito_reclamado text,
    defeito_encontrado text,
    solucao text,
    tecnico_responsavel text,
    praca varchar(50),
    nome_praca varchar(150),
    coordenacao varchar(150),
    id_registro_legado bigint UNIQUE,
    criado_em timestamptz NOT NULL DEFAULT now()
)
"""

CRIAR_INDICES_SQL = (
    f"""
    CREATE INDEX IF NOT EXISTS idx_servicos_manutencao_filial_data
        ON public.{TABELA_SERVICOS_MANUTENCAO_FILIAL} (data_ref)
    """,
    f"""
    CREATE INDEX IF NOT EXISTS idx_servicos_manutencao_filial_dimensoes
        ON public.{TABELA_SERVICOS_MANUTENCAO_FILIAL}
            (contrato, operadora, equipamento)
    """,
)

MIGRAR_TABELA_LEGADA_SQL = f"""
DO $$
BEGIN
    IF to_regclass('public.{TABELA_LEGADA_MANUTENCAO_FILIAL}') IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM (
               VALUES
                   ('id'),
                   ('data_ref'),
                   ('id_contrato'),
                   ('contrato'),
                   ('id_operadora'),
                   ('operadora'),
                   ('cod_equipamento'),
                   ('equipamento'),
                   ('numero_serie'),
                   ('qtd'),
                   ('defeito_reclamado'),
                   ('defeito_encontrado'),
                   ('solucao'),
                   ('tecnico_responsavel')
           ) AS obrigatoria(nome)
           WHERE NOT EXISTS (
               SELECT 1
               FROM information_schema.columns
               WHERE table_schema = 'public'
                 AND table_name = '{TABELA_LEGADA_MANUTENCAO_FILIAL}'
                 AND column_name = obrigatoria.nome
           )
       )
    THEN
        INSERT INTO public.{TABELA_SERVICOS_MANUTENCAO_FILIAL} (
            data_ref,
            data_competencia,
            id_contrato,
            contrato,
            id_operadora,
            operadora,
            id_equipamento,
            equipamento,
            numero_serie,
            id_servico_executado,
            servico_executado,
            qtd_servico,
            defeito_reclamado,
            defeito_encontrado,
            solucao,
            tecnico_responsavel,
            id_registro_legado
        )
        SELECT
            coalesce(legado.data_ref, CURRENT_DATE),
            date_trunc('month', coalesce(legado.data_ref, CURRENT_DATE))::date,
            coalesce(legado.id_contrato, ''),
            coalesce(legado.contrato, ''),
            coalesce(legado.id_operadora, ''),
            coalesce(legado.operadora, ''),
            coalesce(legado.cod_equipamento, ''),
            coalesce(legado.equipamento, ''),
            coalesce(legado.numero_serie, ''),
            '',
            coalesce(
                nullif(trim(legado.solucao), ''),
                nullif(trim(legado.defeito_encontrado), ''),
                'Serviço executado na filial'
            ),
            greatest(coalesce(legado.qtd, 1), 1),
            coalesce(legado.defeito_reclamado, ''),
            coalesce(legado.defeito_encontrado, ''),
            coalesce(legado.solucao, ''),
            coalesce(legado.tecnico_responsavel, ''),
            legado.id
        FROM public.{TABELA_LEGADA_MANUTENCAO_FILIAL} AS legado
        WHERE legado.id IS NOT NULL
        ON CONFLICT (id_registro_legado) DO NOTHING;
    END IF;
END
$$
"""

CONSULTAR_SERVICOS_SQL = f"""
SELECT
    id,
    '{PREFIXO_NUMERO_OS}' || lpad(
        id::text,
        greatest({LARGURA_NUMERO_OS}, length(id::text)),
        '0'
    ) AS numero_os,
    data_ref,
    data_competencia,
    id_contrato,
    contrato,
    id_operadora,
    operadora,
    id_equipamento,
    equipamento,
    numero_serie,
    id_servico_executado,
    servico_executado,
    qtd_servico,
    defeito_reclamado,
    defeito_encontrado,
    solucao,
    tecnico_responsavel,
    praca,
    nome_praca,
    coordenacao,
    criado_em
FROM public.{TABELA_SERVICOS_MANUTENCAO_FILIAL}
ORDER BY data_ref DESC, id DESC
"""

INSERIR_SERVICO_SQL = f"""
INSERT INTO public.{TABELA_SERVICOS_MANUTENCAO_FILIAL} (
    data_ref,
    data_competencia,
    id_contrato,
    contrato,
    id_operadora,
    operadora,
    id_equipamento,
    equipamento,
    numero_serie,
    id_servico_executado,
    servico_executado,
    defeito_reclamado,
    defeito_encontrado,
    solucao,
    tecnico_responsavel,
    praca,
    nome_praca,
    coordenacao
)
VALUES (
    :data_ref,
    :data_competencia,
    :id_contrato,
    :contrato,
    :id_operadora,
    :operadora,
    :id_equipamento,
    :equipamento,
    :numero_serie,
    :id_servico_executado,
    :servico_executado,
    :defeito_reclamado,
    :defeito_encontrado,
    :solucao,
    :tecnico_responsavel,
    :praca,
    :nome_praca,
    :coordenacao
)
RETURNING id
"""


def formatar_numero_os(id_registro: int) -> str:
    return f"{PREFIXO_NUMERO_OS}{id_registro:0{LARGURA_NUMERO_OS}d}"


def _garantir_schema_na_conexao(conn: Connection) -> None:
    conn.execute(text(CRIAR_TABELA_SQL))
    for comando in CRIAR_INDICES_SQL:
        conn.execute(text(comando))
    conn.execute(text(MIGRAR_TABELA_LEGADA_SQL))


def garantir_tabela_servicos_manutencao_filial() -> None:
    with get_engine().begin() as conn:
        _garantir_schema_na_conexao(conn)


def carregar_servicos_manutencao_filial() -> pd.DataFrame:
    garantir_tabela_servicos_manutencao_filial()
    return pd.read_sql(text(CONSULTAR_SERVICOS_SQL), get_engine())


def salvar_servico_manutencao_filial(dados: Mapping[str, object]) -> int:
    with get_engine().begin() as conn:
        _garantir_schema_na_conexao(conn)
        novo_id = conn.execute(text(INSERIR_SERVICO_SQL), dict(dados)).scalar_one()

    return int(novo_id)
