BEGIN;

CREATE TABLE IF NOT EXISTS public.servicos_executados_manutencao_filial (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_ref date NOT NULL,
    data_competencia date NOT NULL,
    id_contrato varchar(50),
    contrato varchar(150) NOT NULL,
    id_operadora varchar(50),
    operadora varchar(150) NOT NULL,
    id_equipamento varchar(50),
    equipamento text NOT NULL,
    numero_serie text,
    id_servico_executado varchar(50),
    servico_executado text NOT NULL,
    qtd_servico integer NOT NULL DEFAULT 1 CHECK (qtd_servico > 0),
    defeito_reclamado text,
    defeito_encontrado text,
    solucao text,
    tecnico_responsavel text,
    praca varchar(50),
    nome_praca varchar(150),
    coordenacao varchar(150),
    id_registro_legado bigint UNIQUE,
    criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_servicos_manutencao_filial_data
    ON public.servicos_executados_manutencao_filial (data_ref);

CREATE INDEX IF NOT EXISTS idx_servicos_manutencao_filial_dimensoes
    ON public.servicos_executados_manutencao_filial
        (contrato, operadora, equipamento);

-- Preserva eventuais registros criados pela versao de teste anterior.
DO $$
BEGIN
    IF to_regclass('public.base_historica_manutencao_filial_teste') IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM (
               VALUES
                   ('id'),
                   ('data_ref'),
                   ('id_contrato'),
                   ('contrato'),
                   ('id_operadora'),
                   ('operadora'),
                   ('cod_equipamento'),
                   ('equipamento'),
                   ('numero_serie'),
                   ('qtd'),
                   ('defeito_reclamado'),
                   ('defeito_encontrado'),
                   ('solucao'),
                   ('tecnico_responsavel')
           ) AS obrigatoria(nome)
           WHERE NOT EXISTS (
               SELECT 1
               FROM information_schema.columns
               WHERE table_schema = 'public'
                 AND table_name = 'base_historica_manutencao_filial_teste'
                 AND column_name = obrigatoria.nome
           )
       )
    THEN
        INSERT INTO public.servicos_executados_manutencao_filial (
            data_ref,
            data_competencia,
            id_contrato,
            contrato,
            id_operadora,
            operadora,
            id_equipamento,
            equipamento,
            numero_serie,
            id_servico_executado,
            servico_executado,
            qtd_servico,
            defeito_reclamado,
            defeito_encontrado,
            solucao,
            tecnico_responsavel,
            id_registro_legado
        )
        SELECT
            coalesce(legado.data_ref, CURRENT_DATE),
            date_trunc('month', coalesce(legado.data_ref, CURRENT_DATE))::date,
            coalesce(legado.id_contrato, ''),
            coalesce(legado.contrato, ''),
            coalesce(legado.id_operadora, ''),
            coalesce(legado.operadora, ''),
            coalesce(legado.cod_equipamento, ''),
            coalesce(legado.equipamento, ''),
            coalesce(legado.numero_serie, ''),
            '',
            coalesce(
                nullif(trim(legado.solucao), ''),
                nullif(trim(legado.defeito_encontrado), ''),
                'Serviço executado na filial'
            ),
            greatest(coalesce(legado.qtd, 1), 1),
            coalesce(legado.defeito_reclamado, ''),
            coalesce(legado.defeito_encontrado, ''),
            coalesce(legado.solucao, ''),
            coalesce(legado.tecnico_responsavel, ''),
            legado.id
        FROM public.base_historica_manutencao_filial_teste AS legado
        WHERE legado.id IS NOT NULL
        ON CONFLICT (id_registro_legado) DO NOTHING;
    END IF;
END
$$;

COMMIT;
